### Processing :-)

In this Notebook, we process all the OD records (with theirs routes generated with Graph Hopper)
to calculate their cycling potential :-)

The final result is the `complete_csv.csv` file, that is the basis of all this reasearch!

In [1]:
# importing data and auxiliar functions

import saopaulo.sp_grid as gr
import saopaulo.cycling_potential as cp
from bikescience.slope import plot_slope, plot_slopes, split_route
from shapely.geometry import LineString
import ast

from math import floor

import folium
import pandas as pd
import geopandas as gpd
from statistics import stdev
from ipywidgets import interact_manual, widgets, fixed
from IPython.core.display import display, HTML, clear_output
import matplotlib.pyplot as plt
import matplotlib.ticker as tkr
import warnings
import requests
import os
warnings.simplefilter('ignore')
import time

zone_shp = gpd.read_file('../data/sao-paulo/od/shapes/Zonas_2017_region.shp')
zone_shp.crs = {'init': 'epsg:31983'}  
zone_shp.to_crs(epsg='4326', inplace=True)

routes_files = {
    'pedestrian':  'routes_pedestrians_to_bikes.csv',
    'car':         'new_routes_cars_to_bikes.csv',
    'bus_inter':   'new_routes_bus_intercity_to_bikes.csv',
    'bus_otherc':  'new_routes_bus_other_cities_to_bikes.csv',
    'bus_private': 'new_routes_bus_private_to_bikes.csv',
    'bus_school':  'new_routes_bus_school_to_bikes.csv',
    'bus_sp':      'new_routes_bus_sp_to_bikes.csv',
    'monorail':    'new_routes_monorail_to_bikes.csv',
    'motorcycle':  'new_routes_motorcycle_to_bikes.csv',
    'other':       'new_routes_other_to_bikes.csv',
    'subway':      'new_routes_subway_to_bikes.csv',
    'taxi_app':    'new_routes_taxi_app_to_bikes.csv',
    'taxi':        'new_routes_taxi_to_bikes.csv',
    'train':       'new_routes_train_to_bikes.csv',
}
    
# read routes files and join with general trips file
od_trips = pd.read_csv('../data/sao-paulo/od/OD_2017.csv')
od_trips.columns = [c[: c.index(',')] for c in od_trips.columns]
od_trips.set_index('ID_ORDEM', inplace=True, drop=False)
display(od_trips)

complete_gdf = gpd.GeoDataFrame()

for modal in routes_files:
    print('importing ' + modal)
    df = pd.read_csv('../data/sao-paulo/rotas-migracao/' + routes_files[modal])
    df.set_index('trip_id', inplace=True, drop=False)
    df = df.join(other = od_trips, how = 'left')
    gdf = gpd.GeoDataFrame(df, crs={'init': 'epsg:4326'}, 
                           geometry=[LineString(ast.literal_eval(r)) for r in df.route])
    gdf['length'] = gdf['geometry'].length * 100000
    gdf['modal'] = modal
    complete_gdf = pd.concat([complete_gdf, gdf])


od_routes_sp = gpd.read_file('../data/sao-paulo/od/routes/bike_routes_in_sp.shp')
od_routes_sp.crs = {'init': 'epsg:4326'}
od_routes_sp['length'] = od_routes_sp['geometry'].length * 100000

the_grid = gr.create(n=10, west_offset=-0.15, east_offset=0.23, north_offset=0.19, south_offset=-0.46)

/home/pedro/.local/lib/python3.8/site-packages/geopandas/_compat.py:106: UserWarning: The Shapely GEOS version (3.8.0-CAPI-1.13.1 ) is incompatible with the GEOS version PyGEOS was compiled with (3.9.0-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(

,ZONA,MUNI_DOM,CO_DOM_X,CO_DOM_Y,ID_DOM,F_DOM,FE_DOM,DOM,CD_ENTRE,DATA,...,DURACAO,MODOPRIN,TIPVG,PAG_VIAG,TP_ESAUTO,VL_EST,PE_BICI,VIA_BICI,TP_ESTBICI,ID_ORDEM
ID_ORDEM,,,,,,,,,,,,,,,,,,,,,
1,1,36,333743,7394463,10001,1,15.416667,1,1,6092017,...,10,16,3,0,0,0.0,1,0,0,1
2,1,36,333743,7394463,10001,0,15.416667,1,1,6092017,...,10,16,3,0,0,0.0,1,0,0,2
3,1,36,333743,7394463,10001,0,15.416667,1,1,6092017,...,50,1,1,2,0,0.0,0,0,0,3
4,1,36,333743,7394463,10001,0,15.416667,1,1,6092017,...,60,1,1,2,0,0.0,0,0,0,4
5,1,36,333743,7394463,10001,0,15.416667,1,1,6092017,...,40,12,2,0,0,0.0,0,0,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183088,517,25,294618,7410518,5171418,0,85.531250,1418,1,15092018,...,30,16,3,0,0,0.0,1,0,0,183088
183089,517,25,295243,7411456,5171599,1,52.500000,1599,1,15092018,...,10,16,3,0,0,0.0,1,0,0,183089
183090,517,25,295243,7411456,5171599,0,52.500000,1599,1,15092018,...,10,16,3,0,0,0.0,1,0,0,183090
183091,517,25,295243,7411456,5171599,0,52.500000,1599,1,15092018,...,5,16,3,0,0,0.0,1,0,0,183091
183092,517,25,295243,7411456,5171599,0,52.500000,1599,1,15092018,...,5,16,3,0,0,0.0,1,0,0,183092

importing pedestrian
importing car
importing bus_inter
importing bus_otherc
importing bus_private
importing bus_school
importing bus_sp
importing monorail
importing motorcycle
importing other
importing subway
importing taxi_app
importing taxi
importing train

In [2]:
complete_gdf = complete_gdf.sort_index()
display(complete_gdf.head(10))

,trip_id,orig_lat,orig_lon,dest_lat,dest_lon,route,distance,num_trips,ZONA,MUNI_DOM,...,PAG_VIAG,TP_ESAUTO,VL_EST,PE_BICI,VIA_BICI,TP_ESTBICI,ID_ORDEM,geometry,length,modal
1.0,1.0,-23.551678,-46.628858,-23.551495,-46.635115,"[[-46.628827, -23.55186, 748.52], [-46.627845,...",1.973649,22.132647,1.0,36.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,"LINESTRING Z (-46.62883 -23.55186 748.52000, -...",1849.286293,pedestrian
2.0,2.0,-23.551495,-46.635115,-23.551678,-46.628858,"[[-46.635147, -23.551546, 783.14], [-46.635381...",1.847881,22.132647,1.0,36.0,...,0.0,0.0,0.0,1.0,0.0,0.0,2.0,"LINESTRING Z (-46.63515 -23.55155 783.14000, -...",1760.427711,pedestrian
3.0,3.0,-23.551678,-46.628858,-23.571829,-46.690238,"[[-46.628827, -23.55186, 748.52], [-46.627845,...",10.045467,18.882487,1.0,36.0,...,2.0,0.0,0.0,0.0,0.0,0.0,3.0,"LINESTRING Z (-46.62883 -23.55186 748.52000, -...",9473.535456,subway
4.0,4.0,-23.571829,-46.690238,-23.525949,-46.666559,"[[-46.690264, -23.571842, 742.26], [-46.691246...",6.921102,18.882487,1.0,36.0,...,2.0,0.0,0.0,0.0,0.0,0.0,4.0,"LINESTRING Z (-46.69026 -23.57184 742.26000, -...",6428.546731,subway
4.0,4.0,-23.525949,-46.666559,-23.537903,-46.670921,"[[-46.666835, -23.525929, 733.11], [-46.666934...",2.850943,18.882487,1.0,36.0,...,2.0,0.0,0.0,0.0,0.0,0.0,4.0,"LINESTRING Z (-46.66683 -23.52593 733.11000, -...",2667.571706,bus_sp
5.0,5.0,-23.537903,-46.670921,-23.551678,-46.628858,"[[-46.670521, -23.538166, 793.48], [-46.669261...",6.916414,18.882487,1.0,36.0,...,0.0,0.0,0.0,0.0,0.0,0.0,5.0,"LINESTRING Z (-46.67052 -23.53817 793.48000, -...",6479.024014,taxi_app
6.0,6.0,-23.552002,-46.628166,-23.551305,-46.631694,"[[-46.628153, -23.552209, 743.23], [-46.627562...",2.055874,22.132647,1.0,36.0,...,0.0,0.0,0.0,1.0,0.0,0.0,6.0,"LINESTRING Z (-46.62815 -23.55221 743.23000, -...",1923.740596,pedestrian
7.0,7.0,-23.551305,-46.631694,-23.552002,-46.628166,"[[-46.632193, -23.551043, 764.21], [-46.632568...",0.772373,22.132647,1.0,36.0,...,0.0,0.0,0.0,1.0,0.0,0.0,7.0,"LINESTRING Z (-46.63219 -23.55104 764.21000, -...",732.073056,pedestrian
8.0,8.0,-23.552002,-46.628166,-23.551305,-46.631694,"[[-46.628153, -23.552209, 743.23], [-46.627562...",2.055874,22.132647,1.0,36.0,...,0.0,0.0,0.0,1.0,0.0,0.0,8.0,"LINESTRING Z (-46.62815 -23.55221 743.23000, -...",1923.740596,pedestrian
9.0,9.0,-23.551305,-46.631694,-23.552002,-46.628166,"[[-46.632193, -23.551043, 764.21], [-46.632568...",0.772373,22.132647,1.0,36.0,...,0.0,0.0,0.0,1.0,0.0,0.0,9.0,"LINESTRING Z (-46.63219 -23.55104 764.21000, -...",732.073056,pedestrian

In [7]:
# conferindo algumas duplicidades

df = pd.read_csv('../data/sao-paulo/rotas-migracao/' + routes_files['bus_sp'])
#df.set_index('trip_id', inplace=True, drop=False)

display(df.loc[df['trip_id'] == 47])

#display(complete_gdf.loc[complete_gdf['ID_ORDEM'] == 47])

,trip_id,orig_lat,orig_lon,dest_lat,dest_lon,route,distance,num_trips
4,47.0,-23.552002,-46.628166,-23.561824,-46.645587,"[[-46.628153, -23.552209, 743.23], [-46.627562...",3.215052,24.079179
8087,47.0,-23.552002,-46.628166,-23.561824,-46.645587,"[[-46.628153, -23.552209, 743.23], [-46.627562...",3.215052,24.079179
8088,47.0,-23.552002,-46.628166,-23.561824,-46.645587,"[[-46.628153, -23.552209, 743.23], [-46.627562...",3.215052,24.079179

- 01 - Metrô
- 02 - Trem
- 03 - Monotrilho
- 04 - Ônibus/micro-ônibus/perua do município de São Paulo
- 05 - Ônibus/micro-ônibus/perua de outros municípios
- 06 - Ônibus/micro-ônibus/perua metropolitano
- 07 - Transporte Fretado
- 08 - Transporte Escolar
- 09 - Dirigindo Automóvel
- 10 - Passageiro de Automóvel
- 11 - Táxi Convencional
- 12 - Táxi não Convencional
- 13 - Dirigindo Moto
- 14 - Passageiro de Moto
- 15 - Bicicleta
- 16 - A Pé
- 17 - Outros

In [3]:
print('BASE ORIGINAL DA OD')

print('Total de viagens:    ', round(sum(od_trips['FE_VIA']))) 
coluna = 'MODOPRIN'

display(od_trips[['FE_VIA', coluna]].groupby(by=coluna).sum().astype(int))


    
    
print('BASE PROCESSADA (separando trechos de cada veículo)')

aux = complete_gdf.loc[complete_gdf['FE_VIA'] > 0]

display(aux[['FE_VIA', 'num_trips', 'modal']].groupby(by='modal').sum().astype(int))

print('TOTAL DE VIAGENS:    ', round(sum(aux['FE_VIA'])))

BASE ORIGINAL DA OD
Total de viagens:     42006660

            FE_VIA
MODOPRIN
0                0
1          3398961
2          1244977
3              653
4          5519488
5          2099062
6           685920
7           251534
8          2093542
9          7811675
10         3529720
11          100342
12          368101
13          967891
14           96218
15          376975
16        13349875
17          111716

BASE PROCESSADA (separando trechos de cada veículo)

               FE_VIA  num_trips
modal
bus_inter     1629413    1629413
bus_otherc    2745547    2745547
bus_private    351980     351980
bus_school    2096602    2096602
bus_sp        8282498    8282498
car          11582847   11582847
monorail         8325       8325
motorcycle    1075839    1075839
other          115141     115141
pedestrian   13349875   13349875
subway        3424909    3424909
taxi           114303     114303
taxi_app       393293     393293
train         2306711    2306711

TOTAL DE VIAGENS:     47477291

In [5]:
potential = []
for i, r in complete_gdf.iterrows():
    if i % 5000 == 0:
        print(i, '-------------------------')
    try:
        pot_d, pot_a, pot_i = 0,0,0#cp.cycling_potential_variables(r)
    except:
        pot_d, pot_a, pot_i = 0,0,0
        print(i, '- broken case')
        # broken cases usually represent inconsistent routes
    potential.append([i, pot_d, pot_a, pot_i, (pot_d + pot_a + pot_i) / 3])
        
#display(potential)

5000.0 -------------------------
10000.0 -------------------------
15000.0 -------------------------
15000.0 -------------------------
25000.0 -------------------------
35000.0 -------------------------
40000.0 -------------------------
40000.0 -------------------------
45000.0 -------------------------
50000.0 -------------------------
60000.0 -------------------------
65000.0 -------------------------
70000.0 -------------------------
80000.0 -------------------------
85000.0 -------------------------
90000.0 -------------------------
90000.0 -------------------------
90000.0 -------------------------
95000.0 -------------------------
105000.0 -------------------------
110000.0 -------------------------
115000.0 -------------------------
120000.0 -------------------------
125000.0 -------------------------
130000.0 -------------------------
135000.0 -------------------------
145000.0 -------------------------
155000.0 -------------------------
160000.0 -------------------------
165000.0 -------------------------
170000.0 -------------------------
180000.0 -------------------------

In [7]:
c = ['id', 'distance_potential', 'age_potential', 'inclination_potential', 'final_potential']
potential_df = pd.DataFrame(potential, columns = c)
potential_df.set_index('id', inplace=True, drop=False)
potential_df = potential_df.sort_index()

display(potential_df.head(10))

,id,distance_potential,age_potential,inclination_potential,final_potential
id,,,,,
1.0,1.0,0,0,0,0.0
2.0,2.0,0,0,0,0.0
3.0,3.0,0,0,0,0.0
4.0,4.0,0,0,0,0.0
4.0,4.0,0,0,0,0.0
5.0,5.0,0,0,0,0.0
6.0,6.0,0,0,0,0.0
7.0,7.0,0,0,0,0.0
8.0,8.0,0,0,0,0.0
9.0,9.0,0,0,0,0.0

In [8]:
complete_gdf_joined = pd.concat([complete_gdf, potential_df], axis=1)
#complete_gdf.join(other = potential_df, how = 'left')
display(complete_gdf_joined.head(10))

,trip_id,orig_lat,orig_lon,dest_lat,dest_lon,route,distance,num_trips,ZONA,MUNI_DOM,...,TP_ESTBICI,ID_ORDEM,geometry,length,modal,id,distance_potential,age_potential,inclination_potential,final_potential
1.0,1.0,-23.551678,-46.628858,-23.551495,-46.635115,"[[-46.628827, -23.55186, 748.52], [-46.627845,...",1.973649,22.132647,1.0,36.0,...,0.0,1.0,"LINESTRING Z (-46.62883 -23.55186 748.52000, -...",1849.286293,pedestrian,1.0,0,0,0,0.0
2.0,2.0,-23.551495,-46.635115,-23.551678,-46.628858,"[[-46.635147, -23.551546, 783.14], [-46.635381...",1.847881,22.132647,1.0,36.0,...,0.0,2.0,"LINESTRING Z (-46.63515 -23.55155 783.14000, -...",1760.427711,pedestrian,2.0,0,0,0,0.0
3.0,3.0,-23.551678,-46.628858,-23.571829,-46.690238,"[[-46.628827, -23.55186, 748.52], [-46.627845,...",10.045467,18.882487,1.0,36.0,...,0.0,3.0,"LINESTRING Z (-46.62883 -23.55186 748.52000, -...",9473.535456,subway,3.0,0,0,0,0.0
4.0,4.0,-23.571829,-46.690238,-23.525949,-46.666559,"[[-46.690264, -23.571842, 742.26], [-46.691246...",6.921102,18.882487,1.0,36.0,...,0.0,4.0,"LINESTRING Z (-46.69026 -23.57184 742.26000, -...",6428.546731,subway,4.0,0,0,0,0.0
4.0,4.0,-23.525949,-46.666559,-23.537903,-46.670921,"[[-46.666835, -23.525929, 733.11], [-46.666934...",2.850943,18.882487,1.0,36.0,...,0.0,4.0,"LINESTRING Z (-46.66683 -23.52593 733.11000, -...",2667.571706,bus_sp,4.0,0,0,0,0.0
5.0,5.0,-23.537903,-46.670921,-23.551678,-46.628858,"[[-46.670521, -23.538166, 793.48], [-46.669261...",6.916414,18.882487,1.0,36.0,...,0.0,5.0,"LINESTRING Z (-46.67052 -23.53817 793.48000, -...",6479.024014,taxi_app,5.0,0,0,0,0.0
6.0,6.0,-23.552002,-46.628166,-23.551305,-46.631694,"[[-46.628153, -23.552209, 743.23], [-46.627562...",2.055874,22.132647,1.0,36.0,...,0.0,6.0,"LINESTRING Z (-46.62815 -23.55221 743.23000, -...",1923.740596,pedestrian,6.0,0,0,0,0.0
7.0,7.0,-23.551305,-46.631694,-23.552002,-46.628166,"[[-46.632193, -23.551043, 764.21], [-46.632568...",0.772373,22.132647,1.0,36.0,...,0.0,7.0,"LINESTRING Z (-46.63219 -23.55104 764.21000, -...",732.073056,pedestrian,7.0,0,0,0,0.0
8.0,8.0,-23.552002,-46.628166,-23.551305,-46.631694,"[[-46.628153, -23.552209, 743.23], [-46.627562...",2.055874,22.132647,1.0,36.0,...,0.0,8.0,"LINESTRING Z (-46.62815 -23.55221 743.23000, -...",1923.740596,pedestrian,8.0,0,0,0,0.0
9.0,9.0,-23.551305,-46.631694,-23.552002,-46.628166,"[[-46.632193, -23.551043, 764.21], [-46.632568...",0.772373,22.132647,1.0,36.0,...,0.0,9.0,"LINESTRING Z (-46.63219 -23.55104 764.21000, -...",732.073056,pedestrian,9.0,0,0,0,0.0

In [ ]:
complete_gdf_joined.to_csv('complete_csv.csv')